function pointMax = weighted_average(S, ri, ci)
pointMax = ((S(ri-1,ci-1)*[ri-1 ci-1] + ...
           S(ri-1,ci)*[ri-1 ci] + ...
           S(ri-1,ci+1)*[ri-1 ci+1] + ...
           S(ri,ci-1)*[ri ci-1] + ...
           S(ri,ci)*[ri ci] + ...
           S(ri,ci+1)*[ri ci+1] + ...
           S(ri+1,ci-1)*[ri+1 ci-1] + ...
           S(ri+1,ci)*[ri+1 ci] + ...
           S(ri+1,ci+1)*[ri+1 ci+1])/ ... 
           (S(ri-1,ci-1)+S(ri-1,ci) + ...
           S(ri-1,ci+1) + S(ri,ci-1) + ...
           S(ri,ci) + S(ri,ci+1) + ...
           S(ri+1,ci-1) + S(ri+1,ci) + ...
           S(ri+1,ci+1)))';
end
